library(knitr)
library(rvest)
library(gsubfn)
library(tidyr)
library(tmap)
library(shiny)
library(readr)
library(dplyr)
library(XML)
library(tidyverse)
library(tidyr)
library(ggplot2)
library(gganimate)
library(tidyverse)
library(tmap)
library(plotly)
library(sf)
library(ggalt)

options(gsubfn.engine="R")

# Uvozimo funkcije za pobiranje in uvoz zemljevida.
source("lib/uvozi.zemljevid.r", encoding="UTF-8")
